const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');

/* Make functions for EVERY kind of table you have
in your database.  They will go here and return an 
array of objects.*/

function makeUsersArray() {
  return [
      {
        "id" : 1,
        "user_name" : "test",
        "password" : "$2a$04$GUu7zKKswojs0zuZ3ac5BuqhGw0hmca6Q06k\/qCPWwmKPfT4k03rG",
        "date_created" : "2020-05-17T17:55:49Z",
        "date_modified" : null
      },
      {
        "id" : 2,
        "user_name" : "WalterCDolenz",
        "password" : "$2a$04$Y3h\/zQ58ZLBEkSdNOp33zu\/AUaX5HDiMkKPJ6p\/62WX1UGg.rniNO",
        "date_created" : "2020-05-17T17:55:49Z",
        "date_modified" : null
      },
      {
        "id" : 3,
        "user_name" : "SerasVictoria",
        "password" : "$2a$04$hvGWuaS.LxMRqo6cNXkrhe48eQyFmmgSXTtsQMI.19PvtKbRB52iC",
        "date_created" : "2020-05-17T17:55:49Z",
        "date_modified" : null
      },
      {
        "id" : 4,
        "user_name" : "Trollmiester",
        "password" : "$2a$04$KzkoCWuFPOYrg9nWarMOOeg9hU.Jo\/ZV.67DvZsydDu0\/B.rOLfea",
        "date_created" : "2020-05-17T17:55:49Z",
        "date_modified" : null
      }
  ];
};

function makeFoldersArray() {
  return [
    {
      "id" : 1,
      "folder_name" : "My Best Team - OU",
      "user_id" : 1,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 2,
      "folder_name" : "Infinite Showcase - OU",
      "user_id" : 1,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 3,
      "folder_name" : "Super Strong Teams",
      "user_id" : 1,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 4,
      "folder_name" : "Sophistocated Teams",
      "user_id" : 2,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 5,
      "folder_name" : "Fun Teams",
      "user_id" : 4,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 6,
      "folder_name" : "Cute Pokemon Teams",
      "user_id" : 3,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 21,
      "folder_name" : "Test Folder 2",
      "user_id" : 4,
      "date_created" : "2020-05-22T20:47:42Z",
      "date_modified" : null
    },
    {
      "id" : 27,
      "folder_name" : "Test Folder",
      "user_id" : 3,
      "date_created" : "2020-05-23T16:40:19Z",
      "date_modified" : null
    },
    {
      "id" : 12,
      "folder_name" : "Stall Teams",
      "user_id" : 1,
      "date_created" : "2020-05-21T15:37:32Z",
      "date_modified" : null
    },
    {
      "id" : 7,
      "folder_name" : "UU Teams",
      "user_id" : 1,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    }
  ];
};

function makeTeamsArray() {
  return [
    {
      "id" : 1,
      "team_name" : "Darkrai's revenge",
      "folder_id" : 2,
      "description" : "A team using Mega Darkrai",
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 2,
      "team_name" : "Troll Team",
      "folder_id" : 5,
      "description" : "I'm just going to use Clefable You know....",
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 3,
      "team_name" : "OU Balance 1",
      "folder_id" : 4,
      "description" : "The best team made",
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 4,
      "team_name" : "Cute Mons Team",
      "folder_id" : 6,
      "description" : "I just wanted Pokemon I thought were the cutest",
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 15,
      "team_name" : "Nasty Gen 8 OU Stall",
      "folder_id" : 1,
      "description" : null,
      "date_created" : "2020-05-21T18:11:23Z",
      "date_modified" : null
    },
    {
      "id" : 16,
      "team_name" : "Mega Arcanine",
      "folder_id" : 2,
      "description" : null,
      "date_created" : "2020-05-21T18:13:04Z",
      "date_modified" : null
    },
    {
      "id" : 17,
      "team_name" : "I Got The Horses In The Back",
      "folder_id" : 2,
      "description" : null,
      "date_created" : "2020-05-21T18:16:46Z",
      "date_modified" : null
    },
    {
      "id" : 18,
      "team_name" : "Cute Team 1",
      "folder_id" : 6,
      "description" : null,
      "date_created" : "2020-05-21T18:43:16Z",
      "date_modified" : null
    },
    {
      "id" : 19,
      "team_name" : "Cute Team 2",
      "folder_id" : 6,
      "description" : null,
      "date_created" : "2020-05-21T18:44:10Z",
      "date_modified" : null
    },
    {
      "id" : 20,
      "team_name" : "Cute Team 3",
      "folder_id" : 6,
      "description" : null,
      "date_created" : "2020-05-21T18:45:18Z",
      "date_modified" : null
    },
    {
      "id" : 22,
      "team_name" : "PIKACHU TEST TEAM",
      "folder_id" : 6,
      "description" : null,
      "date_created" : "2020-05-21T20:20:31Z",
      "date_modified" : null
    },
    {
      "id" : 24,
      "team_name" : "Funny Joke Team",
      "folder_id" : 5,
      "description" : "Everything is so goddamn funny..... just kidding, I'm going to use Clefable\/Corv\/Pex like always lolololol get rekt nub",
      "date_created" : "2020-05-22T01:26:27Z",
      "date_modified" : null
    },
    {
      "id" : 14,
      "team_name" : "Nasty Stall",
      "folder_id" : 12,
      "description" : "This is a team for gen 8 OU",
      "date_created" : "2020-05-21T18:08:04Z",
      "date_modified" : null
    },
    {
      "id" : 30,
      "team_name" : "Test team 2",
      "folder_id" : 21,
      "description" : "a test",
      "date_created" : "2020-05-22T20:49:05Z",
      "date_modified" : null
    },
    {
      "id" : 32,
      "team_name" : "Test",
      "folder_id" : 6,
      "description" : "",
      "date_created" : "2020-05-22T23:09:54Z",
      "date_modified" : null
    },
    {
      "id" : 33,
      "team_name" : "Second Test",
      "folder_id" : 6,
      "description" : "A team from showdown",
      "date_created" : "2020-05-22T23:11:15Z",
      "date_modified" : null
    },
    {
      "id" : 25,
      "team_name" : "UU Power",
      "folder_id" : 7,
      "description" : "A description",
      "date_created" : "2020-05-22T14:07:41Z",
      "date_modified" : null
    },
    {
      "id" : 38,
      "team_name" : "123456",
      "folder_id" : 3,
      "description" : "A variant of the old 123456 Team, but for Pokemon Infinite's metagame",
      "date_created" : "2020-05-24T14:21:03Z",
      "date_modified" : null
    },
    {
      "id" : 40,
      "team_name" : "test team",
      "folder_id" : 12,
      "description" : "",
      "date_created" : "2020-05-25T00:13:20Z",
      "date_modified" : null
    }
  ];
};

function makeSetsArray() {
  return [
    {
      "id" : 1,
      "nickname" : "Aegi Boi",
      "species" : "Aegislash",
      "gender" : "F",
      "item" : "Choice Band",
      "ability" : "Stance Change",
      "level" : 99,
      "shiny" : true,
      "happiness" : 252,
      "nature" : "Brave",
      "hp_ev" : 165,
      "atk_ev" : 252,
      "def_ev" : 8,
      "spa_ev" : 20,
      "spd_ev" : 8,
      "spe_ev" : 56,
      "hp_iv" : 30,
      "atk_iv" : 31,
      "def_iv" : 29,
      "spa_iv" : 0,
      "spd_iv" : 28,
      "spe_iv" : 0,
      "move_one" : "Close Combat",
      "move_two" : "Shadow Claw",
      "move_three" : "Iron Head",
      "move_four" : "Head Smash",
      "team_id" : 4,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 2,
      "nickname" : null,
      "species" : "Darkrai",
      "gender" : null,
      "item" : "Darkraite",
      "ability" : "Bad Dreams",
      "level" : 100,
      "shiny" : true,
      "happiness" : 255,
      "nature" : "Timid",
      "hp_ev" : 0,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 252,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Perdition's Pyre",
      "move_two" : "Dark Void",
      "move_three" : "Nasty Plot",
      "move_four" : "Dark Pulse",
      "team_id" : 1,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 3,
      "nickname" : null,
      "species" : "Zygarde-Complete",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Power Construct",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 0,
      "atk_ev" : 232,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 44,
      "spe_ev" : 232,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Thousand Arrows",
      "move_two" : "Dragon Dance",
      "move_three" : "Substitute",
      "move_four" : "Dragon Tail",
      "team_id" : 1,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 4,
      "nickname" : null,
      "species" : "Groudon-Primal",
      "gender" : null,
      "item" : "Red Orb",
      "ability" : "Desolate Land",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Conscientious",
      "hp_ev" : 248,
      "atk_ev" : 0,
      "def_ev" : 8,
      "spa_ev" : 0,
      "spd_ev" : 252,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 0,
      "move_one" : "Precipice Blades",
      "move_two" : "Stealth Rock",
      "move_three" : "Toxic",
      "move_four" : "Dragon Tail",
      "team_id" : 1,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 5,
      "nickname" : null,
      "species" : "Yveltal",
      "gender" : null,
      "item" : "Safety Goggles",
      "ability" : "Dark Aura",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Fastidious",
      "hp_ev" : 248,
      "atk_ev" : 0,
      "def_ev" : 180,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 80,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Foul Play",
      "move_two" : "Taunt",
      "move_three" : "Roost",
      "move_four" : "Toxic",
      "team_id" : 1,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 6,
      "nickname" : "Water God",
      "species" : "Arceus-Water",
      "gender" : null,
      "item" : "Splash Plate",
      "ability" : "Multitype",
      "level" : 100,
      "shiny" : true,
      "happiness" : 255,
      "nature" : "Meticulous",
      "hp_ev" : 248,
      "atk_ev" : 0,
      "def_ev" : 244,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 16,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Ice Beam",
      "move_two" : "Defog",
      "move_three" : "Recover",
      "move_four" : "Toxic",
      "team_id" : 1,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 7,
      "nickname" : null,
      "species" : "Arceus-Infinite",
      "gender" : null,
      "item" : "Infinitium Z",
      "ability" : "Multitype",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Timid",
      "hp_ev" : 248,
      "atk_ev" : 0,
      "def_ev" : 8,
      "spa_ev" : 0,
      "spd_ev" : 148,
      "spe_ev" : 196,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Gravity Beam",
      "move_two" : "Will-O-Wisp",
      "move_three" : null,
      "move_four" : null,
      "team_id" : 2,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 20,
      "nickname" : null,
      "species" : "Toxapex",
      "gender" : null,
      "item" : "Black Sludge",
      "ability" : "Regenerator",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Calm",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 4,
      "spa_ev" : 0,
      "spd_ev" : 252,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Scald",
      "move_two" : "Toxic Spikes",
      "move_three" : "Recover",
      "move_four" : "Haze",
      "team_id" : 15,
      "date_created" : "2020-05-21T18:11:23Z",
      "date_modified" : null
    },
    {
      "id" : 21,
      "nickname" : null,
      "species" : "Quagsire",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Unaware",
      "level" : 100,
      "shiny" : true,
      "happiness" : 255,
      "nature" : "Impish",
      "hp_ev" : 252,
      "atk_ev" : 4,
      "def_ev" : 252,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Recover",
      "move_two" : "Toxic",
      "move_three" : "Earthquake",
      "move_four" : "Scald",
      "team_id" : 15,
      "date_created" : "2020-05-21T18:11:23Z",
      "date_modified" : null
    },
    {
      "id" : 22,
      "nickname" : null,
      "species" : "Clefable",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Unaware",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Calm",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 4,
      "spd_ev" : 252,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Wish",
      "move_two" : "Heal Bell",
      "move_three" : "Moonblast",
      "move_four" : "Protect",
      "team_id" : 15,
      "date_created" : "2020-05-21T18:11:23Z",
      "date_modified" : null
    },
    {
      "id" : 23,
      "nickname" : null,
      "species" : "Mandibuzz",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Overcoat",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Impish",
      "hp_ev" : 248,
      "atk_ev" : 0,
      "def_ev" : 240,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 20,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Defog",
      "move_two" : "Foul Play",
      "move_three" : "Roost",
      "move_four" : "Toxic",
      "team_id" : 15,
      "date_created" : "2020-05-21T18:11:23Z",
      "date_modified" : null
    },
    {
      "id" : 24,
      "nickname" : null,
      "species" : "Corsola-Galar",
      "gender" : null,
      "item" : "Eviolite",
      "ability" : "Cursed Body",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Bold",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 252,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Strength Sap",
      "move_two" : "Hex",
      "move_three" : "Will-O-Wisp",
      "move_four" : "Stealth Rock",
      "team_id" : 15,
      "date_created" : "2020-05-21T18:11:23Z",
      "date_modified" : null
    },
    {
      "id" : 25,
      "nickname" : null,
      "species" : "Jirachi",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Serene Grace",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Careful",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 224,
      "spe_ev" : 32,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Wish",
      "move_two" : "Zen Headbutt",
      "move_three" : "Protect",
      "move_four" : "Iron Head",
      "team_id" : 15,
      "date_created" : "2020-05-21T18:11:23Z",
      "date_modified" : null
    },
    {
      "id" : 26,
      "nickname" : null,
      "species" : "Tapu Bulu",
      "gender" : null,
      "item" : "Assault Vest",
      "ability" : "Grassy Surge",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 56,
      "spa_ev" : 0,
      "spd_ev" : 200,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 0,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Horn Leech",
      "move_two" : "Stone Edge",
      "move_three" : "Superpower",
      "move_four" : "Play Rough",
      "team_id" : 16,
      "date_created" : "2020-05-21T18:13:04Z",
      "date_modified" : null
    },
    {
      "id" : 27,
      "nickname" : null,
      "species" : "Meloetta-Pirouette",
      "gender" : null,
      "item" : "Life Orb",
      "ability" : "Serene Grace",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Jolly",
      "hp_ev" : 4,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 0,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Retaliate",
      "move_two" : "Ice Punch",
      "move_three" : "Power-Up Punch",
      "move_four" : "Close Combat",
      "team_id" : 16,
      "date_created" : "2020-05-21T18:13:04Z",
      "date_modified" : null
    },
    {
      "id" : 29,
      "nickname" : "Kommo-boom",
      "species" : "Kommo-o",
      "gender" : "F",
      "item" : "Kommonium Z",
      "ability" : "Bulletproof",
      "level" : 100,
      "shiny" : true,
      "happiness" : 255,
      "nature" : "Rash",
      "hp_ev" : 24,
      "atk_ev" : 0,
      "def_ev" : 8,
      "spa_ev" : 232,
      "spd_ev" : 0,
      "spe_ev" : 244,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Clanging Scales",
      "move_two" : "Close Combat",
      "move_three" : "Substitute",
      "move_four" : "Flamethrower",
      "team_id" : 16,
      "date_created" : "2020-05-21T18:13:04Z",
      "date_modified" : null
    },
    {
      "id" : 28,
      "nickname" : null,
      "species" : "Arcanine",
      "gender" : null,
      "item" : "arcaninite",
      "ability" : "Intimidate",
      "level" : 100,
      "shiny" : true,
      "happiness" : 255,
      "nature" : "Jolly",
      "hp_ev" : 0,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Close Combat",
      "move_two" : "Fire Lash",
      "move_three" : "Morning Sun",
      "move_four" : "Extreme Speed",
      "team_id" : 16,
      "date_created" : "2020-05-21T18:13:04Z",
      "date_modified" : null
    },
    {
      "id" : 30,
      "nickname" : null,
      "species" : "Tapu Lele",
      "gender" : null,
      "item" : "Choice Scarf",
      "ability" : "Psychic Surge",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Modest",
      "hp_ev" : 4,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 252,
      "spd_ev" : 0,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Psychic",
      "move_two" : "Shadow Ball",
      "move_three" : "Focus Blast",
      "move_four" : "Moonblast",
      "team_id" : 16,
      "date_created" : "2020-05-21T18:13:04Z",
      "date_modified" : null
    },
    {
      "id" : 31,
      "nickname" : null,
      "species" : "Corsola-Galar",
      "gender" : null,
      "item" : "Eviolite",
      "ability" : "Cursed Body",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Meticulous",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 252,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Strength Sap",
      "move_two" : "Stealth Rock",
      "move_three" : "Hex",
      "move_four" : "Will-O-Wisp",
      "team_id" : 16,
      "date_created" : "2020-05-21T18:13:04Z",
      "date_modified" : null
    },
    {
      "id" : 32,
      "nickname" : "PEGASUS",
      "species" : "Rapidash",
      "gender" : null,
      "item" : "rapidashite",
      "ability" : "Flash Fire",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Jolly",
      "hp_ev" : 0,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Flare Blitz",
      "move_two" : "High Horsepower",
      "move_three" : "Drill Peck",
      "move_four" : "Swords Dance",
      "team_id" : 17,
      "date_created" : "2020-05-21T18:16:46Z",
      "date_modified" : null
    },
    {
      "id" : 33,
      "nickname" : "DIMSDALE",
      "species" : "Mudsdale",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Stamina",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Impish",
      "hp_ev" : 252,
      "atk_ev" : 4,
      "def_ev" : 252,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Shore Up",
      "move_two" : "Earthquake",
      "move_three" : "Stealth Rock",
      "move_four" : "Toxic",
      "team_id" : 17,
      "date_created" : "2020-05-21T18:16:46Z",
      "date_modified" : null
    },
    {
      "id" : 34,
      "nickname" : "ICE MAN",
      "species" : "Silvally-Water",
      "gender" : null,
      "item" : "Water Memory",
      "ability" : "RKS System",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Careful",
      "hp_ev" : 252,
      "atk_ev" : 4,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 252,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Recover",
      "move_two" : "Parting Shot",
      "move_three" : "Multi-Attack",
      "move_four" : "Defog",
      "team_id" : 17,
      "date_created" : "2020-05-21T18:16:46Z",
      "date_modified" : null
    },
    {
      "id" : 35,
      "nickname" : null,
      "species" : "Toxapex",
      "gender" : null,
      "item" : "Black Sludge",
      "ability" : "Regenerator",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Calm",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 4,
      "spa_ev" : 0,
      "spd_ev" : 252,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Scald",
      "move_two" : "Toxic",
      "move_three" : "Recover",
      "move_four" : "Haze",
      "team_id" : 17,
      "date_created" : "2020-05-21T18:16:46Z",
      "date_modified" : null
    },
    {
      "id" : 36,
      "nickname" : null,
      "species" : "Mew",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Synchronize",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Careful",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 224,
      "spe_ev" : 32,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Knock Off",
      "move_two" : "Soft-Boiled",
      "move_three" : "Rapid Spin",
      "move_four" : "Spikes",
      "team_id" : 17,
      "date_created" : "2020-05-21T18:16:46Z",
      "date_modified" : null
    },
    {
      "id" : 37,
      "nickname" : null,
      "species" : "Talonflame",
      "gender" : null,
      "item" : "Flying Gem",
      "ability" : "Gale Wings",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Careful",
      "hp_ev" : 248,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 252,
      "spe_ev" : 8,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Acrobatics",
      "move_two" : "Will-O-Wisp",
      "move_three" : "Bulk Up",
      "move_four" : "Roost",
      "team_id" : 17,
      "date_created" : "2020-05-21T18:16:46Z",
      "date_modified" : null
    },
    {
      "id" : 38,
      "nickname" : null,
      "species" : "Zacian-Crowned",
      "gender" : null,
      "item" : "Rusted Sword",
      "ability" : "Intrepid Sword",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Jolly",
      "hp_ev" : 0,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Swords Dance",
      "move_two" : "Close Combat",
      "move_three" : "Behemoth Blade",
      "move_four" : "Play Rough",
      "team_id" : 18,
      "date_created" : "2020-05-21T18:43:16Z",
      "date_modified" : null
    },
    {
      "id" : 39,
      "nickname" : null,
      "species" : "Zacian-Crowned",
      "gender" : null,
      "item" : "Rusted Sword",
      "ability" : "Intrepid Sword",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Jolly",
      "hp_ev" : 0,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Swords Dance",
      "move_two" : "Ice Fang",
      "move_three" : "Behemoth Blade",
      "move_four" : "Play Rough",
      "team_id" : 18,
      "date_created" : "2020-05-21T18:43:16Z",
      "date_modified" : null
    },
    {
      "id" : 40,
      "nickname" : null,
      "species" : "Rayquaza-Mega",
      "gender" : null,
      "item" : "Choice Band",
      "ability" : "Air Lock",
      "level" : 100,
      "shiny" : true,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 0,
      "atk_ev" : 252,
      "def_ev" : 4,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Dragon Ascent",
      "move_two" : "Earthquake",
      "move_three" : "Extreme Speed",
      "move_four" : "V-create",
      "team_id" : 18,
      "date_created" : "2020-05-21T18:43:16Z",
      "date_modified" : null
    },
    {
      "id" : 41,
      "nickname" : null,
      "species" : "Arceus-Infinite",
      "gender" : null,
      "item" : "timeplate",
      "ability" : "Multitype",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Meticulous",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 240,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 16,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Judgment",
      "move_two" : "Will-O-Wisp",
      "move_three" : "Recover",
      "move_four" : "Defog",
      "team_id" : 18,
      "date_created" : "2020-05-21T18:43:16Z",
      "date_modified" : null
    },
    {
      "id" : 42,
      "nickname" : null,
      "species" : "Ho-Oh",
      "gender" : null,
      "item" : "Safety Goggles",
      "ability" : "Regenerator",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Fastidious",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 204,
      "spa_ev" : 0,
      "spd_ev" : 52,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Sacred Fire",
      "move_two" : "Earthquake",
      "move_three" : "Toxic",
      "move_four" : "Recover",
      "team_id" : 18,
      "date_created" : "2020-05-21T18:43:16Z",
      "date_modified" : null
    },
    {
      "id" : 43,
      "nickname" : null,
      "species" : "Apocalylidae",
      "gender" : null,
      "item" : "Choice Scarf",
      "ability" : "Gravity Well",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Jolly",
      "hp_ev" : 4,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Precipice Blades",
      "move_two" : "Brave Bird",
      "move_three" : "Apocalyptic Maelstrom",
      "move_four" : "Dark Void",
      "team_id" : 18,
      "date_created" : "2020-05-21T18:43:16Z",
      "date_modified" : null
    },
    {
      "id" : 18,
      "nickname" : null,
      "species" : "Corsola-Galar",
      "gender" : null,
      "item" : "Eviolite",
      "ability" : "Cursed Body",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Bold",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 252,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Strength Sap",
      "move_two" : "Hex",
      "move_three" : "Will-O-Wisp",
      "move_four" : "Stealth Rock",
      "team_id" : 14,
      "date_created" : "2020-05-21T18:08:04Z",
      "date_modified" : null
    },
    {
      "id" : 15,
      "nickname" : null,
      "species" : "Quagsire",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Unaware",
      "level" : 100,
      "shiny" : true,
      "happiness" : 255,
      "nature" : "Impish",
      "hp_ev" : 252,
      "atk_ev" : 4,
      "def_ev" : 252,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Recover",
      "move_two" : "Toxic",
      "move_three" : "Earthquake",
      "move_four" : "Scald",
      "team_id" : 14,
      "date_created" : "2020-05-21T18:08:04Z",
      "date_modified" : null
    },
    {
      "id" : 14,
      "nickname" : null,
      "species" : "Toxapex",
      "gender" : null,
      "item" : "Black Sludge",
      "ability" : "Regenerator",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Calm",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 4,
      "spa_ev" : 0,
      "spd_ev" : 252,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Scald",
      "move_two" : "Toxic Spikes",
      "move_three" : "Recover",
      "move_four" : "Haze",
      "team_id" : 14,
      "date_created" : "2020-05-21T18:08:04Z",
      "date_modified" : null
    },
    {
      "id" : 17,
      "nickname" : "",
      "species" : "Mandibuzz",
      "gender" : "F",
      "item" : "Leftovers",
      "ability" : "Overcoat",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Bold",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 252,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Defog",
      "move_two" : "Foul Play",
      "move_three" : "Roost",
      "move_four" : "Toxic",
      "team_id" : 14,
      "date_created" : "2020-05-21T18:08:04Z",
      "date_modified" : null
    },
    {
      "id" : 19,
      "nickname" : "",
      "species" : "Jirachi",
      "gender" : "",
      "item" : "Leftovers",
      "ability" : "Serene Grace",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Careful",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 224,
      "spe_ev" : 32,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Wish",
      "move_two" : "Zen Headbutt",
      "move_three" : "Protect",
      "move_four" : "Iron Head",
      "team_id" : 14,
      "date_created" : "2020-05-21T18:08:04Z",
      "date_modified" : null
    },
    {
      "id" : 44,
      "nickname" : null,
      "species" : "Rayquaza-Mega",
      "gender" : null,
      "item" : "Choice Band",
      "ability" : "Air Lock",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Jolly",
      "hp_ev" : 0,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Dragon Ascent",
      "move_two" : "Earthquake",
      "move_three" : "V-create",
      "move_four" : "Dragon Claw",
      "team_id" : 19,
      "date_created" : "2020-05-21T18:44:10Z",
      "date_modified" : null
    },
    {
      "id" : 45,
      "nickname" : null,
      "species" : "Apocalylidae",
      "gender" : null,
      "item" : "Choice Scarf",
      "ability" : "Gravity Well",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 4,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Precipice Blades",
      "move_two" : "Brave Bird",
      "move_three" : "Apocalyptic Maelstrom",
      "move_four" : "Power Whip",
      "team_id" : 19,
      "date_created" : "2020-05-21T18:44:10Z",
      "date_modified" : null
    },
    {
      "id" : 46,
      "nickname" : null,
      "species" : "Xerneas",
      "gender" : null,
      "item" : "Safety Goggles",
      "ability" : "Fairy Aura",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Meticulous",
      "hp_ev" : 248,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 8,
      "spd_ev" : 252,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Defog",
      "move_two" : "Toxic",
      "move_three" : "Moonblast",
      "move_four" : "Rest",
      "team_id" : 19,
      "date_created" : "2020-05-21T18:44:10Z",
      "date_modified" : null
    },
    {
      "id" : 48,
      "nickname" : null,
      "species" : "Groudon-Primal",
      "gender" : null,
      "item" : "Red Orb",
      "ability" : "Desolate Land",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Mild",
      "hp_ev" : 24,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 252,
      "spd_ev" : 104,
      "spe_ev" : 128,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Rock Polish",
      "move_two" : "Hidden Power [Ice]",
      "move_three" : "Precipice Blades",
      "move_four" : "Fire Blast",
      "team_id" : 19,
      "date_created" : "2020-05-21T18:44:10Z",
      "date_modified" : null
    },
    {
      "id" : 47,
      "nickname" : null,
      "species" : "Arceus-Water",
      "gender" : null,
      "item" : "Splash Plate",
      "ability" : "Multitype",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Meticulous",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 240,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 16,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Ice Beam",
      "move_two" : "Toxic",
      "move_three" : "Perish Song",
      "move_four" : "Recover",
      "team_id" : 19,
      "date_created" : "2020-05-21T18:44:10Z",
      "date_modified" : null
    },
    {
      "id" : 49,
      "nickname" : null,
      "species" : "Necrozma-Dusk-Mane",
      "gender" : null,
      "item" : "Safety Goggles",
      "ability" : "Prism Armor",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Fastidious",
      "hp_ev" : 252,
      "atk_ev" : 4,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 252,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Stealth Rock",
      "move_two" : "Morning Sun",
      "move_three" : "Sunsteel Strike",
      "move_four" : "Toxic",
      "team_id" : 19,
      "date_created" : "2020-05-21T18:44:10Z",
      "date_modified" : null
    },
    {
      "id" : 50,
      "nickname" : null,
      "species" : "Kyurem-Omnipotent",
      "gender" : null,
      "item" : "Choice Specs",
      "ability" : "Omniforge",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Naive",
      "hp_ev" : 0,
      "atk_ev" : 4,
      "def_ev" : 0,
      "spa_ev" : 252,
      "spd_ev" : 0,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Origin Flare",
      "move_two" : "Earth Power",
      "move_three" : "Ice Beam",
      "move_four" : "Blue Flare",
      "team_id" : 20,
      "date_created" : "2020-05-21T18:45:18Z",
      "date_modified" : null
    },
    {
      "id" : 51,
      "nickname" : null,
      "species" : "Xerneas",
      "gender" : null,
      "item" : "Fairium Z",
      "ability" : "Fairy Aura",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Meticulous",
      "hp_ev" : 248,
      "atk_ev" : 0,
      "def_ev" : 252,
      "spa_ev" : 0,
      "spd_ev" : 8,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Geomancy",
      "move_two" : "Moonblast",
      "move_three" : "Rest",
      "move_four" : "Ingrain",
      "team_id" : 20,
      "date_created" : "2020-05-21T18:45:18Z",
      "date_modified" : null
    },
    {
      "id" : 52,
      "nickname" : null,
      "species" : "Arceus-Infinite",
      "gender" : null,
      "item" : "timeplate",
      "ability" : "Multitype",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Meticulous",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 240,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 16,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Judgment",
      "move_two" : "Will-O-Wisp",
      "move_three" : "Recover",
      "move_four" : "Defog",
      "team_id" : 20,
      "date_created" : "2020-05-21T18:45:18Z",
      "date_modified" : null
    },
    {
      "id" : 53,
      "nickname" : null,
      "species" : "Groudon-Primal",
      "gender" : null,
      "item" : "Red Orb",
      "ability" : "Desolate Land",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 144,
      "atk_ev" : 156,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 56,
      "spe_ev" : 152,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Stone Edge",
      "move_two" : "Inner Power Ice",
      "move_three" : "Precipice Blades",
      "move_four" : "Swords Dance",
      "team_id" : 20,
      "date_created" : "2020-05-21T18:45:18Z",
      "date_modified" : null
    },
    {
      "id" : 54,
      "nickname" : null,
      "species" : "Necrozma-Dusk-Mane",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Prism Armor",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Fastidious",
      "hp_ev" : 252,
      "atk_ev" : 4,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 252,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Stealth Rock",
      "move_two" : "Morning Sun",
      "move_three" : "Sunsteel Strike",
      "move_four" : "Toxic",
      "team_id" : 20,
      "date_created" : "2020-05-21T18:45:18Z",
      "date_modified" : null
    },
    {
      "id" : 55,
      "nickname" : null,
      "species" : "Apocalylidae",
      "gender" : null,
      "item" : "Choice Scarf",
      "ability" : "Gravity Well",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 4,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Precipice Blades",
      "move_two" : "Brave Bird",
      "move_three" : "Apocalyptic Maelstrom",
      "move_four" : "Power Whip",
      "team_id" : 20,
      "date_created" : "2020-05-21T18:45:18Z",
      "date_modified" : null
    },
    {
      "id" : 62,
      "nickname" : null,
      "species" : "Pikachu",
      "gender" : null,
      "item" : null,
      "ability" : null,
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 0,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Tackle",
      "move_two" : null,
      "move_three" : null,
      "move_four" : null,
      "team_id" : 22,
      "date_created" : "2020-05-21T20:20:40Z",
      "date_modified" : null
    },
    {
      "id" : 69,
      "nickname" : null,
      "species" : "Pikachu",
      "gender" : null,
      "item" : null,
      "ability" : null,
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 0,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Tackle",
      "move_two" : null,
      "move_three" : null,
      "move_four" : null,
      "team_id" : 4,
      "date_created" : "2020-05-21T21:10:18Z",
      "date_modified" : null
    },
    {
      "id" : 70,
      "nickname" : null,
      "species" : "Clefable",
      "gender" : null,
      "item" : "Life Orb",
      "ability" : "Magic Guard",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Mild",
      "hp_ev" : 76,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 252,
      "spd_ev" : 0,
      "spe_ev" : 180,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Moonblast",
      "move_two" : "Moonlight",
      "move_three" : "Fire Blast",
      "move_four" : "Thunderbolt",
      "team_id" : 24,
      "date_created" : "2020-05-22T01:26:27Z",
      "date_modified" : null
    },
    {
      "id" : 71,
      "nickname" : null,
      "species" : "Corviknight",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Pressure",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Jolly",
      "hp_ev" : 252,
      "atk_ev" : 4,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Brave Bird",
      "move_two" : "Roost",
      "move_three" : "Bulk Up",
      "move_four" : "Substitute",
      "team_id" : 24,
      "date_created" : "2020-05-22T01:26:27Z",
      "date_modified" : null
    },
    {
      "id" : 72,
      "nickname" : null,
      "species" : "Hydreigon",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Levitate",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Timid",
      "hp_ev" : 0,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 252,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Dark Pulse",
      "move_two" : "Substitute",
      "move_three" : "Nasty Plot",
      "move_four" : "Flash Cannon",
      "team_id" : 24,
      "date_created" : "2020-05-22T01:26:27Z",
      "date_modified" : null
    },
    {
      "id" : 74,
      "nickname" : null,
      "species" : "Excadrill",
      "gender" : null,
      "item" : "Life Orb",
      "ability" : "Sand Rush",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Jolly",
      "hp_ev" : 0,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Earthquake",
      "move_two" : "Swords Dance",
      "move_three" : "Iron Head",
      "move_four" : "Rock Slide",
      "team_id" : 24,
      "date_created" : "2020-05-22T01:26:27Z",
      "date_modified" : null
    },
    {
      "id" : 75,
      "nickname" : null,
      "species" : "Hippowdon",
      "gender" : null,
      "item" : "Smooth Rock",
      "ability" : "Sand Stream",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Impish",
      "hp_ev" : 252,
      "atk_ev" : 4,
      "def_ev" : 252,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Earthquake",
      "move_two" : "Whirlwind",
      "move_three" : "Slack Off",
      "move_four" : "Stealth Rock",
      "team_id" : 24,
      "date_created" : "2020-05-22T01:26:27Z",
      "date_modified" : null
    },
    {
      "id" : 76,
      "nickname" : null,
      "species" : "Celesteela",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Beast Boost",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Conscientious",
      "hp_ev" : 248,
      "atk_ev" : 0,
      "def_ev" : 28,
      "spa_ev" : 0,
      "spd_ev" : 232,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Leech Seed",
      "move_two" : "Flamethrower",
      "move_three" : "Heavy Slam",
      "move_four" : "Protect",
      "team_id" : 25,
      "date_created" : "2020-05-22T14:07:41Z",
      "date_modified" : null
    },
    {
      "id" : 77,
      "nickname" : null,
      "species" : "Keldeo",
      "gender" : null,
      "item" : "Choice Scarf",
      "ability" : "Justified",
      "level" : 100,
      "shiny" : true,
      "happiness" : 255,
      "nature" : "Timid",
      "hp_ev" : 0,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 252,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Hydro Pump",
      "move_two" : "Air Slash",
      "move_three" : "Secret Sword",
      "move_four" : "Scald",
      "team_id" : 25,
      "date_created" : "2020-05-22T14:07:41Z",
      "date_modified" : null
    },
    {
      "id" : 78,
      "nickname" : null,
      "species" : "Starmie",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Regenerator",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Timid",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Recover",
      "move_two" : "Rapid Spin",
      "move_three" : "Scald",
      "move_four" : "Thunder Wave",
      "team_id" : 25,
      "date_created" : "2020-05-22T14:07:41Z",
      "date_modified" : null
    },
    {
      "id" : 79,
      "nickname" : null,
      "species" : "Altaria",
      "gender" : null,
      "item" : "Altarianite",
      "ability" : "Natural Cure",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 248,
      "atk_ev" : 160,
      "def_ev" : 4,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 96,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Return",
      "move_two" : "Roost",
      "move_three" : "Inner Power Fire",
      "move_four" : "Earthquake",
      "team_id" : 25,
      "date_created" : "2020-05-22T14:07:41Z",
      "date_modified" : null
    },
    {
      "id" : 80,
      "nickname" : null,
      "species" : "Chesnaught",
      "gender" : null,
      "item" : "Grassium Z",
      "ability" : "Battle Bond",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 252,
      "atk_ev" : 140,
      "def_ev" : 116,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Spiky Shield",
      "move_two" : "Spikes",
      "move_three" : "Wood Hammer",
      "move_four" : "Drain Punch",
      "team_id" : 25,
      "date_created" : "2020-05-22T14:07:41Z",
      "date_modified" : null
    },
    {
      "id" : 81,
      "nickname" : null,
      "species" : "Gorochu",
      "gender" : null,
      "item" : "Choice Band",
      "ability" : "Electric Surge",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 0,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Extreme Speed",
      "move_two" : "Zippy Zap",
      "move_three" : "Volt Tackle",
      "move_four" : "Sucker Punch",
      "team_id" : 25,
      "date_created" : "2020-05-22T14:07:41Z",
      "date_modified" : null
    },
    {
      "id" : 73,
      "nickname" : "Cancer",
      "species" : "Toxapex",
      "gender" : "F",
      "item" : "Leftovers",
      "ability" : "Regenerator",
      "level" : 100,
      "shiny" : true,
      "happiness" : 255,
      "nature" : "Bold",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 252,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Recover",
      "move_two" : "Scald",
      "move_three" : "Toxic Spikes",
      "move_four" : "Haze",
      "team_id" : 24,
      "date_created" : "2020-05-22T01:26:27Z",
      "date_modified" : null
    },
    {
      "id" : 86,
      "nickname" : null,
      "species" : "Pikachu",
      "gender" : null,
      "item" : null,
      "ability" : null,
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 0,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Tackle",
      "move_two" : null,
      "move_three" : null,
      "move_four" : null,
      "team_id" : 30,
      "date_created" : "2020-05-22T20:49:44Z",
      "date_modified" : null
    },
    {
      "id" : 87,
      "nickname" : null,
      "species" : "Klefki",
      "gender" : null,
      "item" : "Light Clay",
      "ability" : "Prankster",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Calm",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 4,
      "spa_ev" : 0,
      "spd_ev" : 252,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Reflect",
      "move_two" : "Foul Play",
      "move_three" : "Metal Shard",
      "move_four" : "Light Screen",
      "team_id" : 33,
      "date_created" : "2020-05-22T23:11:16Z",
      "date_modified" : null
    },
    {
      "id" : 88,
      "nickname" : null,
      "species" : "Deoxys-Defense",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Pressure",
      "level" : 100,
      "shiny" : true,
      "happiness" : 255,
      "nature" : "Timid",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 32,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 224,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Spikes",
      "move_two" : "Stealth Rock",
      "move_three" : "Recover",
      "move_four" : "Taunt",
      "team_id" : 33,
      "date_created" : "2020-05-22T23:11:16Z",
      "date_modified" : null
    },
    {
      "id" : 89,
      "nickname" : null,
      "species" : "Obstagoon",
      "gender" : null,
      "item" : "Touga Berry",
      "ability" : "Guts",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 4,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Belly Drum",
      "move_two" : "Seed Bomb",
      "move_three" : "Extreme Speed",
      "move_four" : "Knock Off",
      "team_id" : 33,
      "date_created" : "2020-05-22T23:11:16Z",
      "date_modified" : null
    },
    {
      "id" : 90,
      "nickname" : null,
      "species" : "Frosmoth",
      "gender" : null,
      "item" : "Heavy-Duty Boots",
      "ability" : "Ice Scales",
      "level" : 100,
      "shiny" : true,
      "happiness" : 255,
      "nature" : "Modest",
      "hp_ev" : 0,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 252,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Fiery Dance",
      "move_two" : "Bug Buzz",
      "move_three" : "Ice Beam",
      "move_four" : "Quiver Dance",
      "team_id" : 33,
      "date_created" : "2020-05-22T23:11:16Z",
      "date_modified" : null
    },
    {
      "id" : 91,
      "nickname" : null,
      "species" : "Gorochu",
      "gender" : null,
      "item" : "Choice Band",
      "ability" : "Electric Surge",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 0,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Extreme Speed",
      "move_two" : "Zippy Zap",
      "move_three" : "Volt Tackle",
      "move_four" : "Sucker Punch",
      "team_id" : 33,
      "date_created" : "2020-05-22T23:11:16Z",
      "date_modified" : null
    },
    {
      "id" : 92,
      "nickname" : null,
      "species" : "Ampharos-Mega",
      "gender" : null,
      "item" : "Ampharosite",
      "ability" : "Mold Breaker",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Modest",
      "hp_ev" : 0,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 252,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Tail Glow",
      "move_two" : "Dragon Pulse",
      "move_three" : "Thunderbolt",
      "move_four" : "Agility",
      "team_id" : 33,
      "date_created" : "2020-05-22T23:11:16Z",
      "date_modified" : null
    },
    {
      "id" : 93,
      "nickname" : null,
      "species" : "Deoxys-Defense",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Pressure",
      "level" : 100,
      "shiny" : true,
      "happiness" : 255,
      "nature" : "Timid",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 32,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 224,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Spikes",
      "move_two" : "Stealth Rock",
      "move_three" : "Recover",
      "move_four" : "Taunt",
      "team_id" : 32,
      "date_created" : "2020-05-22T23:11:49Z",
      "date_modified" : null
    },
    {
      "id" : 114,
      "nickname" : null,
      "species" : "Pikachu",
      "gender" : null,
      "item" : null,
      "ability" : null,
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 0,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Tackle",
      "move_two" : null,
      "move_three" : null,
      "move_four" : null,
      "team_id" : 40,
      "date_created" : "2020-05-25T00:13:23Z",
      "date_modified" : null
    },
    {
      "id" : 100,
      "nickname" : null,
      "species" : "Arceus-Infinite",
      "gender" : null,
      "item" : "Infinitium Z",
      "ability" : "Multitype",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Timid",
      "hp_ev" : 248,
      "atk_ev" : 0,
      "def_ev" : 8,
      "spa_ev" : 0,
      "spd_ev" : 148,
      "spe_ev" : 96,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Gravity Beam",
      "move_two" : "Perish Song",
      "move_three" : "Recover",
      "move_four" : "Will-O-Wisp",
      "team_id" : 1,
      "date_created" : "2020-05-24T02:10:43Z",
      "date_modified" : null
    },
    {
      "id" : 16,
      "nickname" : null,
      "species" : "Clefable",
      "gender" : null,
      "item" : "Leftovers",
      "ability" : "Unaware",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Calm",
      "hp_ev" : 252,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 4,
      "spd_ev" : 252,
      "spe_ev" : 0,
      "hp_iv" : 31,
      "atk_iv" : 0,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Wish",
      "move_two" : "Heal Bell",
      "move_three" : "Moonblast",
      "move_four" : "Protect",
      "team_id" : 14,
      "date_created" : "2020-05-21T18:08:04Z",
      "date_modified" : null
    },
    {
      "id" : 102,
      "nickname" : "1",
      "species" : "Tyranitar-Gmax",
      "gender" : null,
      "item" : "Focus Sash",
      "ability" : "Sand Stream",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Naive",
      "hp_ev" : 0,
      "atk_ev" : 40,
      "def_ev" : 0,
      "spa_ev" : 216,
      "spd_ev" : 0,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Stealth Rock",
      "move_two" : "Crunch",
      "move_three" : "Ice Beam",
      "move_four" : "Stone Edge",
      "team_id" : 38,
      "date_created" : "2020-05-24T14:21:03Z",
      "date_modified" : null
    },
    {
      "id" : 104,
      "nickname" : "2",
      "species" : "Excadrill",
      "gender" : null,
      "item" : "Air Balloon",
      "ability" : "Sand Rush",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 32,
      "atk_ev" : 252,
      "def_ev" : 8,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 216,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Rapid Spin",
      "move_two" : "Rock Slide",
      "move_three" : "Iron Head",
      "move_four" : "Earthquake",
      "team_id" : 38,
      "date_created" : "2020-05-24T14:21:03Z",
      "date_modified" : null
    },
    {
      "id" : 103,
      "nickname" : "3",
      "species" : "Greninja-Ash",
      "gender" : "M",
      "item" : "Choice Specs",
      "ability" : "Battle Bond",
      "level" : 100,
      "shiny" : true,
      "happiness" : 255,
      "nature" : "Timid",
      "hp_ev" : 0,
      "atk_ev" : 0,
      "def_ev" : 0,
      "spa_ev" : 252,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Hydro Pump",
      "move_two" : "Spikes",
      "move_three" : "Dark Pulse",
      "move_four" : "Water Shuriken",
      "team_id" : 38,
      "date_created" : "2020-05-24T14:21:03Z",
      "date_modified" : null
    },
    {
      "id" : 105,
      "nickname" : "4",
      "species" : "Rapidash",
      "gender" : null,
      "item" : "rapidashite",
      "ability" : "Flash Fire",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Jolly",
      "hp_ev" : 0,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Flare Blitz",
      "move_two" : "High Horsepower",
      "move_three" : "Drill Peck",
      "move_four" : "Swords Dance",
      "team_id" : 38,
      "date_created" : "2020-05-24T14:21:03Z",
      "date_modified" : null
    },
    {
      "id" : 106,
      "nickname" : "5",
      "species" : "Kommo-o",
      "gender" : null,
      "item" : "Kommonium Z",
      "ability" : "Bulletproof",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Hasty",
      "hp_ev" : 4,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 0,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Flamethrower",
      "move_two" : "Poison Jab",
      "move_three" : "Close Combat",
      "move_four" : "Clanging Scales",
      "team_id" : 38,
      "date_created" : "2020-05-24T14:21:03Z",
      "date_modified" : null
    },
    {
      "id" : 107,
      "nickname" : "6 (Gorochu)",
      "species" : "Gorochu",
      "gender" : null,
      "item" : "Choice Band",
      "ability" : "Electric Surge",
      "level" : 100,
      "shiny" : false,
      "happiness" : 255,
      "nature" : "Adamant",
      "hp_ev" : 0,
      "atk_ev" : 252,
      "def_ev" : 0,
      "spa_ev" : 0,
      "spd_ev" : 4,
      "spe_ev" : 252,
      "hp_iv" : 31,
      "atk_iv" : 31,
      "def_iv" : 31,
      "spa_iv" : 31,
      "spd_iv" : 31,
      "spe_iv" : 31,
      "move_one" : "Extreme Speed",
      "move_two" : "Zippy Zap",
      "move_three" : "Volt Tackle",
      "move_four" : "Sucker Punch",
      "team_id" : 38,
      "date_created" : "2020-05-24T14:21:03Z",
      "date_modified" : null
    }
  ];
};

function makeFavoritesArray() { // will not actually be used, but I'll make it anyways for now.
  return [
    {
      "id" : 1,
      "team_id" : 3,
      "user_id" : 1,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 2,
      "team_id" : 3,
      "user_id" : 2,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 3,
      "team_id" : 3,
      "user_id" : 3,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 4,
      "team_id" : 3,
      "user_id" : 4,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 5,
      "team_id" : 4,
      "user_id" : 1,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 6,
      "team_id" : 4,
      "user_id" : 2,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 7,
      "team_id" : 4,
      "user_id" : 3,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 8,
      "team_id" : 4,
      "user_id" : 4,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 9,
      "team_id" : 1,
      "user_id" : 1,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    },
    {
      "id" : 10,
      "team_id" : 1,
      "user_id" : 4,
      "date_created" : "2020-05-17T17:55:49Z",
      "date_modified" : null
    }
  ];
};


/* Next, make functions that return objects of 
expected items you might make.  This will likely match
the services you have.  One or more should be malicious*/

function makeFolder (users, folders) {

  // need to go get things

  return {
    id: folder.id,
    folder_name: folder.folder_name,
    user_id: user.id,
    date_created: folder.date_created,
    date_modified: folder.date_modified
  };
};

function makeTeam (users, folders, teams) {

  // need to go get things

  return {
    id: 1,
    team_name: "Darkrai's revenge",
    description: "A team using Mega Darkrai",
    date_created: "Sun May 17 2020 13:55:49 GMT-0400 (Eastern Daylight Time)",
    date_modified: "",
    user_id: 1,
    user_name: "test",
    folder_id: 2,
    folder_name: "Infinite Showcase - OU"
  }
};

function makeSet (users, folders, teams, sets, id) {

  // need to go get things

  return {
    id: 2,
    team_name: "Darkrai's revenge",
    description: "A team using Mega Darkrai",
    date_created: "Sun May 17 2020 13:55:49 GMT-0400 (Eastern Daylight Time)",
    date_modified: "",
    user_id: 1,
    user_name: "test",
    folder_id: 2,
    folder_name: "Infinite Showcase - OU",
    nickname: "",
    species: "Darkrai",
    gender: "Darkrai",
    item: "Darkraite",
    ability: "Bad Dreams",
    level: "100",
    shiny: true,
    happiness: "255",
    nature: "Timid",
    hp_ev: "",
    atk_ev: "",
    def_ev: "",
    spa_ev: "252",
    spd_ev: "4",
    spe_ev: "252",
    hp_iv: "31",
    atk_iv: "31",
    def_iv: "31",
    spa_iv: "31",
    spd_iv: "31",
    spe_iv: "31",
    move_one: "Perdition's Pyre",
    move_two: "Dark Void",
    move_three: "Nasty Plot",
    move_four: "Dark Pulse",
    team_id: 1
  }
};

// need to make malicious versions of these.

// skipping favorites

/* Next, make a Fixtures function that creates a fixture of the
collection of the arrays as single entities.*/

function makeFixtures() {
  const testUsers = makeUsersArray();
  const testFolders = makeFoldersArray();
  const testTeams = makeTestsArray();
  const testSets = makeSetsArray();

  return {testUsers, testFolders, testTeams, testSets}
}

/* Next, Make a clean table that truncates all the tables in your 
test db and RESTART IDENTIY CASCADE at the end*/ 

function cleanTables(db) {
  return db.raw(
    `TRUNCATE
      users,
      folders,
      teams,
      sets,
      favorites
      RESTART IDENTITY CASCADE`
  )
}


/* Finally, make tables that seed your database.  You will have
a seedUsers function already made for you below, as well as the 
AuthHeader function*/


function seedUsers(db, users) {
  const hashedUsers = users.map(user => ({
    ...user,
    password: bcrypt.hashSync(user.password, 1)
  }));
  return db.into('users').insert(hashedUsers)
    .then(() => {

    });
};

// rest of seeding


function makeAuthHeader(user, secret = process.env.JWT_SECRET) {
  const token = jwt.sign({}, secret, {
    subject: user.user_name,
    algorithm: 'HS256',
  });
  return `Bearer ${token}`;
};

module.exports = {
  makeUsersArray,
  makeFoldersArray,
  makeTeamsArray,
  makeSetsArray,
  makeFavoritesArray,
  makeFolder,
  makeTeam,
  makeSet,

  makeFixtures,
  cleanTables,
  seedUsers,
  seedFolders,
  seedTeams,
  seedSets,
  
  makeAuthHeader
}