/* CLEAN UP USERS */
ALTER TABLE users DROP CONSTRAINT users_pkey;
ALTER TABLE users DROP COLUMN IF EXISTS id;
ALTER TABLE users RENAME COLUMN user_uuid TO id;
ALTER TABLE users ADD PRIMARY KEY (id);
